// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mikitachab/score-board/db (interfaces: RepositoryInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	db "github.com/mikitachab/score-board/db"
	reflect "reflect"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAllPlayers mocks base method
func (m *MockRepositoryInterface) GetAllPlayers() []db.Player {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPlayers")
	ret0, _ := ret[0].([]db.Player)
	return ret0
}

// GetAllPlayers indicates an expected call of GetAllPlayers
func (mr *MockRepositoryInterfaceMockRecorder) GetAllPlayers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPlayers", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAllPlayers))
}

// GetAllPlays mocks base method
func (m *MockRepositoryInterface) GetAllPlays() []db.Play {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPlays")
	ret0, _ := ret[0].([]db.Play)
	return ret0
}

// GetAllPlays indicates an expected call of GetAllPlays
func (mr *MockRepositoryInterfaceMockRecorder) GetAllPlays() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPlays", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAllPlays))
}

// GetPlayScoresForPlay mocks base method
func (m *MockRepositoryInterface) GetPlayScoresForPlay(arg0 db.Play) []db.PlayScore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayScoresForPlay", arg0)
	ret0, _ := ret[0].([]db.PlayScore)
	return ret0
}

// GetPlayScoresForPlay indicates an expected call of GetPlayScoresForPlay
func (mr *MockRepositoryInterfaceMockRecorder) GetPlayScoresForPlay(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayScoresForPlay", reflect.TypeOf((*MockRepositoryInterface)(nil).GetPlayScoresForPlay), arg0)
}
